const ACTION_TYPES = {
  COLLECTION_FETCH_TRIGGER: '@LDP/COLLECTION_FETCH_TRIGGER',
  COLLECTION_FETCH_SUCCESS: '@LDP/COLLECTION_FETCH_SUCCESS',
  COLLECTION_FETCH_FAILURE: '@LDP/COLLECTION_FETCH_FAILURE',
  ADD_TO_COLLECTION: '@LDP/ADD_TO_COLLECTION',
  REMOVE_FROM_COLLECTION: '@LDP/REMOVE_FROM_COLLECTION'
};

export default ACTION_TYPES;
