const ACTION_TYPES = {
  RESOURCE_FETCH_TRIGGER: '@LDP/RESOURCE_FETCH_TRIGGER',
  RESOURCE_FETCH_SUCCESS: '@LDP/RESOURCE_FETCH_SUCCESS',
  RESOURCE_FETCH_FAILURE: '@LDP/RESOURCE_FETCH_FAILURE',
  SPARQL_QUERY_TRIGGER: '@LDP/SPARQL_QUERY_TRIGGER',
  SPARQL_QUERY_SUCCESS: '@LDP/SPARQL_QUERY_SUCCESS',
  SPARQL_QUERY_FAILURE: '@LDP/SPARQL_QUERY_FAILURE',
  ADD_RESOURCE: '@LDP/ADD_RESOURCE',
  EDIT_RESOURCE: '@LDP/EDIT_RESOURCE',
  DELETE_RESOURCE: '@LDP/DELETE_RESOURCE',
  ADD_TO_CONTAINER: '@LDP/ADD_TO_CONTAINER',
  REMOVE_FROM_CONTAINER: '@LDP/REMOVE_FROM_CONTAINER',
  ADD_TO_COLLECTION: '@LDP/ADD_TO_COLLECTION',
  REMOVE_FROM_COLLECTION: '@LDP/REMOVE_FROM_COLLECTION'
};

export default ACTION_TYPES;
